name: Main

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    container: node:16.6.0-alpine3.13
    services:
      mongo:
        image: mongo
    steps:
      - uses: actions/checkout@v2

      - run: npm ic

      - run: npm run lint

      - run: npm run test
        env:
          MONGODB_URI: "mongodb://mongo:27017/indiweb"

  publish:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2

      - uses: docker/metadata-action@v3
        id: meta
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=sha
          flavor: |
            latest=true

      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}

      - uses: docker/build-push-action@v2
        id: image
        with:
          context: .
          # push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: |
            user/app:latest

      - name: Set image version
        run: sed -i s%latest%${{ steps.meta.outputs.version }}@${{ steps.image.outputs.digest }}% knative.yaml

      - uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.K8S }}
        with:
          args: apply -f knative.yaml
